version: 1
checks:
    - name: tests
      run: go test ./...
    - name: lint
      run: go vet ./...
    - name: ci:ci:test-matrix.os:go-env
      run: go env
    - name: ci:ci:test-matrix.os:verify-gofmt
      run: bash -lc "set -euo pipefail\nfiles=$(find . -name '*.go' -type f)\nif [ -n \"$files\" ]; then\n  bad=$(gofmt -l $files)\n  if [ -n \"$bad\" ]; then\n    echo \"gofmt needed on:\"\n    echo \"$bad\"\n    exit 1\n  fi\nfi"
insults:
    mode: snarky
    file: assets/insults/default.json
    locale: en
banter:
    file: assets/banter/default.json
    locale: en
